name: Run mypy validation
on:
  push:
    branches: [main]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run mypy verification
        run: |
          pip install -r requirements.txt
          pip install "mypy==1.15.0" boto3 pytest && mypy *.py app/*.py tests/*.py
